name: PR Check - Terraform Validation
on:
  workflow_call:
    inputs:
      test_file:
        description: 'The test file to use'
        required: false
        type: string
        default: 'plan.tftest.hcl'

env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  validate:
    runs-on:
      - ubuntu-latest
    timeout-minutes: 5
    env:
      TFDOCS_VERSION: v0.19.0
      TFLINT_VERSION: v0.53.0
    
    steps:
      - uses: actions/checkout@v4

      - name: Install tflint
        run: |
          wget -nv -O /dev/shm/tflint.zip https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip
          unzip -d $HOME/bin /dev/shm/tflint.zip
          echo "$HOME/bin" >> $GITHUB_PATH
          echo tflint -v

      - name: Install terraform-docs
        run: |
          wget -nv -O https://github.com/terraform-docs/terraform-docs/releases/download/${TFDOCS_VERSION}/terraform-docs-${TFDOCS_VERSION}-linux-amd64.tar.gz | tar -zxvf - -C $HOME/bin terraform-docs
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Add cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
    
      - name: Initialize pre-commit
        run: pre-commit install

      - name: Pre-commit check
        run: |
          pre-commit run --color=always --all-files -v
    
      - name: Terraform format
        id: fmt
        run: terraform fmt -check  
        
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform validate
        id: validate
        run: terraform validate  

      - name: Terraform test
        run: |
          if [ -f "tests/${{ github.event.inputs.test_file }}" ]; then
            terraform test -filter=tests/${{ github.event.inputs.test_file }}
          else
            echo "::notice file=${{ github.event.inputs.test_file }}::Terraform test file not found."
          fi